### ISSUE TITLE
Feedback - Lab 8

### ISSUE THREAD

**Issue by TylerofArk** [ijkeller/city-explorer-api#5]
Isaiah,

It's looking really clean so far. Same with your front-end side. Everything is organized nicely, I like your formatting better than mine. I was trying to use the same code that you have on line 102 on your front end but was unable to get it to work for me. Luckily, we got it fixed in code review today.

Looks like after a little work on your server side you will be caught up. Best of luck. Let me know if I can help in any way. 

Cheers,
Tyler

**Comment by ijkeller** [comment]
Thanks
